apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-all
spec:
  containers:
  - name: demo
    image: busybox
    command: ["sh", "-c", "env && sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-config
